extends: eslint:recommended
parserOptions:
    ecmaVersion: 6
    sourceType: module
env:
    amd: true
    browser: true
    es6: true
globals:
    Box2D: false
    keycodeDictionary: false
    Stats: false
    THREE: false
    THREEx: false
